### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mbrn** [aviskarkc10/file-exporter#1]
Could you show me sample that show what is `data:string` parameter in `downloadCSV(data, fileName)`?

For example: How can i export data?
```javascript
const data = [
{name: 'mehmet', surname: 'baran'},
{name: 'Aviskar', surname: 'KC'},
];
downloadCSV(data, fileName)
`

**Comment by aviskarkc10** [comment]
The data should actually look like this:
```
"name,surname
aviskar,kc
mehmet,burram
"
```
I don't have the feature of converting array of objects to string. But I think I should add it. If you are in urgent need you can use the `convertArrayOfObjectsToCSV`  from https://halistechnology.com/2015/05/28/use-javascript-to-export-your-data-as-csv/

**Comment by mbrn** [comment]
@aviskarkc10  thanks for your reply. I will try with `convertArrayOfObjectsToCSV`

**Comment by aviskarkc10** [comment]
@mbrn You can use the `downloadCSVFromArray` function for your use case.
https://github.com/aviskarkc10/file-exporter#examples

**Comment by mbrn** [comment]
Thank you @aviskarkc10 . I will use.
